name = "BoundedLeastSquares"
uuid = "95df6a61-002c-412f-b798-c25124fa4bbf"
authors = ["Nick Boyd <nickboyd@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
