name = "BoundedLeastSquares"
uuid = "95df6a61-002c-412f-b798-c25124fa4bbf"
authors = ["Nick Boyd <nickboyd@gmail.com>"]
version = "0.1.0"

[deps]
LBFGSB = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
