name = "BoundedLeastSquares"
uuid = "95df6a61-002c-412f-b798-c25124fa4bbf"
authors = ["Nick Boyd <nickboyd@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
